"""Configuración global de pytest."""
import sys
from pathlib import Path

# Añadir el directorio raíz del proyecto al path
sys.path.insert(0, str(Path(__file__).parent.parent))

# ── Generar fixture sample.tcx si no existe ──────────────────────────
_FIXTURES_DIR = Path(__file__).parent / "fixtures"
_SAMPLE_TCX = _FIXTURES_DIR / "sample.tcx"

if not _SAMPLE_TCX.exists():
    _FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    _SAMPLE_TCX.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<TrainingCenterDatabase\n'
        '  xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2"\n'
        '  xmlns:ext="http://www.garmin.com/xmlschemas/ActivityExtension/v2">\n'
        '  <Activities>\n'
        '    <Activity Sport="Biking">\n'
        '      <Id>2026-01-15T08:00:00Z</Id>\n'
        '      <Lap StartTime="2026-01-15T08:00:00Z">\n'
        '        <TotalTimeSeconds>600</TotalTimeSeconds>\n'
        '        <DistanceMeters>5000</DistanceMeters>\n'
        '        <Calories>120</Calories>\n'
        '        <Track>\n'
        '          <Trackpoint>\n'
        '            <Time>2026-01-15T08:00:00Z</Time>\n'
        '            <Position>\n'
        '              <LatitudeDegrees>40.4168</LatitudeDegrees>\n'
        '              <LongitudeDegrees>-3.7038</LongitudeDegrees>\n'
        '            </Position>\n'
        '            <AltitudeMeters>650</AltitudeMeters>\n'
        '            <DistanceMeters>0</DistanceMeters>\n'
        '            <HeartRateBpm><Value>120</Value></HeartRateBpm>\n'
        '            <Cadence>85</Cadence>\n'
        '            <Extensions>\n'
        '              <ext:TPX>\n'
        '                <ext:Watts>200</ext:Watts>\n'
        '                <ext:Speed>8.3</ext:Speed>\n'
        '              </ext:TPX>\n'
        '            </Extensions>\n'
        '          </Trackpoint>\n'
        '          <Trackpoint>\n'
        '            <Time>2026-01-15T08:01:00Z</Time>\n'
        '            <Position>\n'
        '              <LatitudeDegrees>40.4170</LatitudeDegrees>\n'
        '              <LongitudeDegrees>-3.7035</LongitudeDegrees>\n'
        '            </Position>\n'
        '            <AltitudeMeters>655</AltitudeMeters>\n'
        '            <DistanceMeters>500</DistanceMeters>\n'
        '            <HeartRateBpm><Value>135</Value></HeartRateBpm>\n'
        '            <Cadence>90</Cadence>\n'
        '            <Extensions>\n'
        '              <ext:TPX>\n'
        '                <ext:Watts>250</ext:Watts>\n'
        '                <ext:Speed>8.5</ext:Speed>\n'
        '              </ext:TPX>\n'
        '            </Extensions>\n'
        '          </Trackpoint>\n'
        '          <Trackpoint>\n'
        '            <Time>2026-01-15T08:02:00Z</Time>\n'
        '            <Position>\n'
        '              <LatitudeDegrees>40.4175</LatitudeDegrees>\n'
        '              <LongitudeDegrees>-3.7030</LongitudeDegrees>\n'
        '            </Position>\n'
        '            <AltitudeMeters>660</AltitudeMeters>\n'
        '            <DistanceMeters>1000</DistanceMeters>\n'
        '            <HeartRateBpm><Value>142</Value></HeartRateBpm>\n'
        '            <Cadence>88</Cadence>\n'
        '            <Extensions>\n'
        '              <ext:TPX>\n'
        '                <ext:Watts>280</ext:Watts>\n'
        '                <ext:Speed>8.7</ext:Speed>\n'
        '              </ext:TPX>\n'
        '            </Extensions>\n'
        '          </Trackpoint>\n'
        '          <Trackpoint>\n'
        '            <Time>2026-01-15T08:05:00Z</Time>\n'
        '            <Position>\n'
        '              <LatitudeDegrees>40.4180</LatitudeDegrees>\n'
        '              <LongitudeDegrees>-3.7020</LongitudeDegrees>\n'
        '            </Position>\n'
        '            <AltitudeMeters>670</AltitudeMeters>\n'
        '            <DistanceMeters>2500</DistanceMeters>\n'
        '            <HeartRateBpm><Value>155</Value></HeartRateBpm>\n'
        '            <Cadence>92</Cadence>\n'
        '            <Extensions>\n'
        '              <ext:TPX>\n'
        '                <ext:Watts>300</ext:Watts>\n'
        '                <ext:Speed>9.0</ext:Speed>\n'
        '              </ext:TPX>\n'
        '            </Extensions>\n'
        '          </Trackpoint>\n'
        '          <Trackpoint>\n'
        '            <Time>2026-01-15T08:10:00Z</Time>\n'
        '            <Position>\n'
        '              <LatitudeDegrees>40.4190</LatitudeDegrees>\n'
        '              <LongitudeDegrees>-3.7010</LongitudeDegrees>\n'
        '            </Position>\n'
        '            <AltitudeMeters>680</AltitudeMeters>\n'
        '            <DistanceMeters>5000</DistanceMeters>\n'
        '            <HeartRateBpm><Value>160</Value></HeartRateBpm>\n'
        '            <Cadence>95</Cadence>\n'
        '            <Extensions>\n'
        '              <ext:TPX>\n'
        '                <ext:Watts>320</ext:Watts>\n'
        '                <ext:Speed>9.5</ext:Speed>\n'
        '              </ext:TPX>\n'
        '            </Extensions>\n'
        '          </Trackpoint>\n'
        '        </Track>\n'
        '      </Lap>\n'
        '    </Activity>\n'
        '  </Activities>\n'
        '</TrainingCenterDatabase>\n',
        encoding="utf-8",
    )
